version: "3"

services:
  webserver:
    image: altimofeev/webserver-localhost
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - .:${WORKDIR}
      - sock:${SOCKET_DIR}

  app:
    image: altimofeev/php-fpm
    env_file:
      - .env
    working_dir: ${WORKDIR}
    volumes:
      - .:${WORKDIR}
      - sock:${SOCKET_DIR}

  postgres:
    container_name: ${DB_HOST}
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


volumes:
  sock:



